SELECT * FROM emp2;

ALTER TABLE emp2 ADD DECIMAL INT;


INSERT INTO emp2(FIRSTNAME,LASTNAME,SALARY,STATUS) VALUES ('XYZ','PQR',30000,'Active');
INSERT INTO emp2(FIRSTNAME,LASTNAME,SALARY,STATUS) VALUES ('LMN','ABC',50000,'InActive');
INSERT INTO emp2(FIRSTNAME,LASTNAME,SALARY,STATUS,DEPATMENTID,DECIMAL) VALUES ('PQR','DTR',40000,'InActive',01,235.415);
INSERT INTO emp2 (FIRSTNAME,LASTNAME,SALARY,STATUS,DEPATMENTID,DECIMAL) VALUES ('JNL','NHK',70000,'InActive',03,415.22);

SELECT * FROM emp2;

SELECT SUBSTRING(FIRSTNAME, 1, 5) AS ExtractString FROM emp2;
SELECT SUBSTRING('XYZ', 1, 100) AS ExtractString;
SELECT TRANSLATE('3*[2+1]/{8-4}', '[]{}', '()()');
SELECT ROUND(235.415, 2, 1) AS RoundValue;
SELECT ROUND(235.415, -1) AS RoundValue;
SELECT CHAR(25) AS CodeToCharacter;

SELECT SALARY+10000 as new_salary FROM emp2;
SELECT SALARY+DECIMAL as added_salary FROM emp2;

SELECT SALARY-5500 as Subtracted_Sal FROM emp2;
SELECT SALARY*15 as Multiplied_Salary FROM emp2;
SELECT SALARY/50 as Sal_Div FROM emp2;
SELECT SALARY%50 as Sal_Div FROM emp2;

SELECT * FROM emp2;

CREATE VIEW [XYZ FIRSTNAME] AS
SELECT FIRSTNAME,LASTNAME 
FROM emp2
WHERE FIRSTNAME = 'XYZ';


SELECT * FROM [XYZ FIRSTNAME];

CREATE VIEW [DECIMAL Above Average SALARY] AS
SELECT FIRSTNAME,LASTNAME
FROM emp2
WHERE SALARY > (SELECT AVG(SALARY) FROM emp2);

SELECT * FROM [DECIMAL Above Average SALARY];

DROP VIEW [XYZ FIRSTNAME];
SELECT * FROM emp2;